name: Notion Synchronization

on:
  issues:
    types:
      - opened
      - reopened
      - edited
      - closed
      - assigned
      - unassigned
      - labeled
      - unlabeled

concurrency:
  group: Notion Synchronization
  cancel-in-progress: true

env:
  ISSUE_URL: ${{ github.event.issue.html_url }}

jobs:
  check-existence:
    runs-on: ubuntu-latest
    outputs:
      page_id: ${{ steps.notion.outputs.page_id }}
      status: ${{ steps.notion.outputs.status }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check notion database
        id: notion
        run: |
          results=$(curl -X POST "https://api.notion.com/v1/databases/${{ secrets.NOTION_DATABASE_ID }}/query" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "filter": {
                "property": "Link",
                "url": {
                  "equals": "$ISSUE_URL"
                }
              },
              "page_size": 1
            }' | jq -r '.results');

            page_id=""
            status=""

            if [ "$results" != "[]" ]; then
              page_id=$(echo "$results" | jq -r '.[0].id')
              status=$(echo "$results" | jq -r '.[0].properties.Status.select.name')
            fi

            echo "page_id=$page_id" >> $GITHUB_OUTPUT
            echo "status=$status" >> $GITHUB_OUTPUT

  synchronize-with-notion:
    needs: check-existence
    name: Synchronize with Notion
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Setup page peoperties
        id: properties
        env:
          CREATED_AT: ${{ github.event.issue.created_at }}
          CLOSED_AT: ${{ github.event.issue.closed_at }}
        run: |
          status="${{ needs.check-existence.outputs.status }}"
          assignees=$(echo '${{ toJSON(github.event.issue.assignees.*.login) }}' | jq '[.[] | {name: .}]' | jq -c .)
          labels=$(echo '${{ toJSON(github.event.issue.labels.*.name) }}' | jq '[.[] | {name: .}]' | jq -c .)
          date=$(echo '{
            "start": "$CREATED_AT",
            "end": "$end",
            "time_zone": "${{ vars.TIMEZONE }}"
          }' | jq -c .)

          if [ "$CLOSED_AT" != "" ]; then
            status="Closed"
            date=$(echo "$date" | jq '.end="$CLOSED_AT"' | jq -c .)
          else
            status="Opened"
          fi

          echo "status=$status" >> $GITHUB_OUTPUT
          echo "assignees=$assignees" >> $GITHUB_OUTPUT
          echo "labels=$labels" >> $GITHUB_OUTPUT
          echo "date=$date" >> $GITHUB_OUTPUT

      - name: Setup parameters
        id: params
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "{}" > body.json
          method="PATCH"
          request_url="https://api.notion.com/v1/pages"

          if [ "${{ needs.check-existence.outputs.page_id }}" != "" ]; then
            request_url+="/${{ needs.check-existence.outputs.page_id }}"
          fi

          if [ "${{ needs.check-existence.outputs.page_id }}" == "" -a "${{ steps.properties.outputs.status }}" == "Opened" ]; then
            method="POST"
            body=$(jq '. + { parent: { database_id: "${{ secrets.NOTION_DATABASE_ID }}" } }' body.json)
            echo "$body" > body.json
          fi

          body=$(jq '. + {
            properties: {
              Status: {
                select: {
                  name: "${{ steps.properties.outputs.status }}"
                }
              },
              Title: {
                title: [{
                  text: {
                    content: "$ISSUE_TITLE"
                  }
                }]
              },
              Assignees: {
                multi_select: ${{ steps.properties.outputs.assignees }}
              },
              Labels: {
                multi_select: ${{ steps.properties.outputs.labels }}
              },
              Date: {
                date: ${{ steps.properties.outputs.date }}
              },
              Link: {
                url: "$ISSUE_URL"
              }
            }
          }' body.json)

          echo "$body" > body.json

          echo "method=$method" >> $GITHUB_OUTPUT
          echo "request_url=$request_url" >> $GITHUB_OUTPUT
          echo "body=$(echo "$(cat body.json)" | jq -c .)" >> $GITHUB_OUTPUT

      - name: Synchronize page properties with Notion
        id: sync
        if: ${{ !(needs.check-existence.outputs.page_id == '' && steps.params.outputs.method == 'PATCH') }}
        run: |
          result=$(curl -X ${{ steps.params.outputs.method }} "${{ steps.params.outputs.request_url }}" \
            -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '${{ steps.params.outputs.body }}')

          url=$(echo "$result" | jq -r '.url')
          prefix=$(echo "$result" | jq -r '.properties.ID.unique_id.prefix')
          number=$(echo "$result" | jq -r '.properties.ID.unique_id.number')

          echo "url=$url" >> $GITHUB_OUTPUT
          echo "id=$prefix-$number" >> $GITHUB_OUTPUT

      - name: Comment on issue
        if: ${{ needs.check-existence.outputs.page_id == '' }}
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |
            **_Synchronized Notion page_**
            > :id: **`${{ steps.sync.outputs.id }}`**
            > :rocket: ${{ steps.sync.outputs.url }}
